
using ParsaPoolad.Domain.Entities.IdealCrm;
using Microsoft.EntityFrameworkCore;
using System.Threading;
using System.Threading.Tasks;

namespace ParsaPoolad.Application.Interfaces.Contexts
{
    public interface IIdealCrmDataBaseContext
    {

        //ParsaPoolad
        
        DbSet<ParsaPooladMenus> ParsaPooladMenus { get; set; }

        //CRM
        DbSet<City> City { get; set; }
        DbSet<CityLang> CityLang { get; set; }
        DbSet<Country> Country { get; set; }
        DbSet<CountryLang> CountryLang { get; set; }
        DbSet<CrmAddressing> CrmAddressing { get; set; }
        DbSet<CrmAddressingType> CrmAddressingType { get; set; }
        DbSet<CrmBankingAccountType> CrmBankingAccountType { get; set; }
        DbSet<CrmBankingAccounts> CrmBankingAccounts { get; set; }
        DbSet<CrmBankingBanks> CrmBankingBanks { get; set; }
        DbSet<CrmBankingBranches> CrmBankingBranches { get; set; }
        DbSet<CrmCallBlackList> CrmCallBlackList { get; set; }
        DbSet<CrmCallHistory> CrmCallHistory { get; set; }
        DbSet<CrmCallType> CrmCallType { get; set; }
        DbSet<CrmCallTypeLang> CrmCallTypeLang { get; set; }
        DbSet<CrmCmsComments> CrmCmsComments { get; set; }
        DbSet<CrmCmsCommentsLang> CrmCmsCommentsLang { get; set; }
        DbSet<CrmCmsFiles> CrmCmsFiles { get; set; }
        DbSet<CrmCmsFilesLang> CrmCmsFilesLang { get; set; }
        DbSet<CrmCmsGallery> CrmCmsGallery { get; set; }
        DbSet<CrmCmsGalleryItems> CrmCmsGalleryItems { get; set; }
        DbSet<CrmCmsGalleryItemsLang> CrmCmsGalleryItemsLang { get; set; }
        DbSet<CrmCmsGalleryLang> CrmCmsGalleryLang { get; set; }
        DbSet<CrmCmsLikes> CrmCmsLikes { get; set; }
        DbSet<CrmCmsMenus> CrmCmsMenus { get; set; }
        DbSet<CrmCmsMenusLang> CrmCmsMenusLang { get; set; }
        DbSet<CrmCmsNews> CrmCmsNews { get; set; }
        DbSet<CrmCmsNewsGroups> CrmCmsNewsGroups { get; set; }
        DbSet<CrmCmsNewsGroupsLang> CrmCmsNewsGroupsLang { get; set; }
        DbSet<CrmCmsNewsLang> CrmCmsNewsLang { get; set; }
        DbSet<CrmCmsObjectTypes> CrmCmsObjectTypes { get; set; }
        DbSet<CrmCmsPages> CrmCmsPages { get; set; }
        DbSet<CrmCmsPagesLang> CrmCmsPagesLang { get; set; }
        DbSet<CrmCompany> CrmCompany { get; set; }
        DbSet<CrmCompanyForbiddenCity> CrmCompanyForbiddenCity { get; set; }
        DbSet<CrmCompanyForbiddenCompany> CrmCompanyForbiddenCompany { get; set; }
        DbSet<CrmCompanyForbiddenDepartment> CrmCompanyForbiddenDepartment { get; set; }
        DbSet<CrmCompanyForbiddenGroup> CrmCompanyForbiddenGroup { get; set; }
        DbSet<CrmCompanyForbiddenGroupIv> CrmCompanyForbiddenGroupIv { get; set; }
        DbSet<CrmCompanyForbiddenProvince> CrmCompanyForbiddenProvince { get; set; }
        DbSet<CrmCompanyForbiddenSubGroup> CrmCompanyForbiddenSubGroup { get; set; }
        DbSet<CrmCompanyGroups> CrmCompanyGroups { get; set; }
        DbSet<CrmCompanyGroupsIi> CrmCompanyGroupsIi { get; set; }
        DbSet<CrmCompanyGroupsIiLang> CrmCompanyGroupsIiLang { get; set; }
        DbSet<CrmCompanyGroupsIii> CrmCompanyGroupsIii { get; set; }
        DbSet<CrmCompanyGroupsIiiLang> CrmCompanyGroupsIiiLang { get; set; }
        DbSet<CrmCompanyGroupsIv> CrmCompanyGroupsIv { get; set; }
        DbSet<CrmCompanyGroupsIvLang> CrmCompanyGroupsIvLang { get; set; }
        DbSet<CrmCompanyGroupsLang> CrmCompanyGroupsLang { get; set; }
        DbSet<CrmCompanyGroupsMulti> CrmCompanyGroupsMulti { get; set; }
        DbSet<CrmCompanyGroupsMultiLang> CrmCompanyGroupsMultiLang { get; set; }
        DbSet<CrmCompanyJustAccessCity> CrmCompanyJustAccessCity { get; set; }
        DbSet<CrmCompanyJustAccessCompany> CrmCompanyJustAccessCompany { get; set; }
        DbSet<CrmCompanyJustAccessDepartment> CrmCompanyJustAccessDepartment { get; set; }
        DbSet<CrmCompanyJustAccessGroup> CrmCompanyJustAccessGroup { get; set; }
        DbSet<CrmCompanyJustAccessGroupIv> CrmCompanyJustAccessGroupIv { get; set; }
        DbSet<CrmCompanyJustAccessProvince> CrmCompanyJustAccessProvince { get; set; }
        DbSet<CrmCompanyJustAccessSubGroup> CrmCompanyJustAccessSubGroup { get; set; }
        DbSet<CrmCompanyLang> CrmCompanyLang { get; set; }
        DbSet<CrmCompanyLoGo> CrmCompanyLoGo { get; set; }
        DbSet<CrmCompanyMultiGroups> CrmCompanyMultiGroups { get; set; }
        DbSet<CrmCompanyPersons> CrmCompanyPersons { get; set; }
        DbSet<CrmCompanyPersonsLang> CrmCompanyPersonsLang { get; set; }
        DbSet<CrmCompanyPersonsTemplate> CrmCompanyPersonsTemplate { get; set; }
        DbSet<CrmCompanyPersonsTemplateLang> CrmCompanyPersonsTemplateLang { get; set; }
        DbSet<CrmCompanyPersonsTmp> CrmCompanyPersonsTmp { get; set; }
        DbSet<CrmCompanyPersonsTmpLang> CrmCompanyPersonsTmpLang { get; set; }
        DbSet<CrmCompanyPictureAlbums> CrmCompanyPictureAlbums { get; set; }
        DbSet<CrmCompanyPictures> CrmCompanyPictures { get; set; }
        DbSet<CrmCompanyPresentation> CrmCompanyPresentation { get; set; }
        DbSet<CrmCompanyPresentationLang> CrmCompanyPresentationLang { get; set; }
        DbSet<CrmCompanySubGroups> CrmCompanySubGroups { get; set; }
        DbSet<CrmCompanySubGroupsLang> CrmCompanySubGroupsLang { get; set; }
        DbSet<CrmCompanyTitle> CrmCompanyTitle { get; set; }
        DbSet<CrmCompanyTitleLang> CrmCompanyTitleLang { get; set; }
        DbSet<CrmCompanyTmp> CrmCompanyTmp { get; set; }
        DbSet<CrmCompanyTmpLang> CrmCompanyTmpLang { get; set; }
        DbSet<CrmCompanyType> CrmCompanyType { get; set; }
        DbSet<CrmCompanyTypeLang> CrmCompanyTypeLang { get; set; }
        DbSet<CrmCompanyUserForbidden> CrmCompanyUserForbidden { get; set; }
        DbSet<CrmConversation> CrmConversation { get; set; }
        DbSet<CrmConversationDefaultContext> CrmConversationDefaultContext { get; set; }
        DbSet<CrmConversationDefaultContextLang> CrmConversationDefaultContextLang { get; set; }
        DbSet<CrmConversationLang> CrmConversationLang { get; set; }
        DbSet<CrmConversationPriority> CrmConversationPriority { get; set; }
        DbSet<CrmConversationPriorityLang> CrmConversationPriorityLang { get; set; }
        DbSet<CrmConversationReferUsers> CrmConversationReferUsers { get; set; }
        DbSet<CrmConversationStatus> CrmConversationStatus { get; set; }
        DbSet<CrmConversationStatusGroups> CrmConversationStatusGroups { get; set; }
        DbSet<CrmConversationStatusGroupsLang> CrmConversationStatusGroupsLang { get; set; }
        DbSet<CrmConversationStatusLang> CrmConversationStatusLang { get; set; }
        DbSet<CrmConversationTmp> CrmConversationTmp { get; set; }
        DbSet<CrmConversationTmpLang> CrmConversationTmpLang { get; set; }
        DbSet<CrmConversationTopics> CrmConversationTopics { get; set; }
        DbSet<CrmConversationTopicsLang> CrmConversationTopicsLang { get; set; }
        DbSet<CrmDyFormFieldMasterValueDetails> CrmDyFormFieldMasterValueDetails { get; set; }
        DbSet<CrmDyFormFieldMasterValues> CrmDyFormFieldMasterValues { get; set; }
        DbSet<CrmDyFormFieldTypes> CrmDyFormFieldTypes { get; set; }
        DbSet<CrmDyFormFieldTypesLang> CrmDyFormFieldTypesLang { get; set; }
        DbSet<CrmDyFormFieldValues> CrmDyFormFieldValues { get; set; }
        DbSet<CrmDyFormFieldValuesLang> CrmDyFormFieldValuesLang { get; set; }
        DbSet<CrmDyFormFields> CrmDyFormFields { get; set; }
        DbSet<CrmDyFormFieldsLang> CrmDyFormFieldsLang { get; set; }
        DbSet<CrmDyFormRegularExpressions> CrmDyFormRegularExpressions { get; set; }
        DbSet<CrmDyFormRegularExpressionsLang> CrmDyFormRegularExpressionsLang { get; set; }
        DbSet<CrmDyFormUserAccess> CrmDyFormUserAccess { get; set; }
        DbSet<CrmDyFormWorkflowSteps> CrmDyFormWorkflowSteps { get; set; }
        DbSet<CrmDyFormWorkflowStepsLang> CrmDyFormWorkflowStepsLang { get; set; }
        DbSet<CrmDyFormWorkflows> CrmDyFormWorkflows { get; set; }
        DbSet<CrmDyFormWorkflowsLang> CrmDyFormWorkflowsLang { get; set; }
        DbSet<CrmDyForms> CrmDyForms { get; set; }
        DbSet<CrmDyFormsLang> CrmDyFormsLang { get; set; }
        DbSet<CrmFileDirectoryType> CrmFileDirectoryType { get; set; }
        DbSet<CrmFileDirectoryTypeLang> CrmFileDirectoryTypeLang { get; set; }
        DbSet<CrmFileDirectoryTypeOpr> CrmFileDirectoryTypeOpr { get; set; }
        DbSet<CrmFileDirectoryTypeOprLang> CrmFileDirectoryTypeOprLang { get; set; }
        DbSet<CrmFilesDirectory> CrmFilesDirectory { get; set; }
        DbSet<CrmFilesDirectoryLang> CrmFilesDirectoryLang { get; set; }
        DbSet<CrmFilesDirectoryTemplate> CrmFilesDirectoryTemplate { get; set; }
        DbSet<CrmFilesDirectoryTemplateType> CrmFilesDirectoryTemplateType { get; set; }
        DbSet<CrmFoSetting> CrmFoSetting { get; set; }
        DbSet<CrmFoSettingLang> CrmFoSettingLang { get; set; }
        DbSet<CrmFund> CrmFund { get; set; }
        DbSet<CrmFundGroups> CrmFundGroups { get; set; }
        DbSet<CrmFundGroupsLang> CrmFundGroupsLang { get; set; }
        DbSet<CrmFundLang> CrmFundLang { get; set; }
        DbSet<CrmImportFromExcel> CrmImportFromExcel { get; set; }
        DbSet<CrmImportFromExcelFields> CrmImportFromExcelFields { get; set; }
        DbSet<CrmInternalMessage> CrmInternalMessage { get; set; }
        DbSet<CrmInternalMessageDefaultContext> CrmInternalMessageDefaultContext { get; set; }
        DbSet<CrmInternalMessageDefaultContextLang> CrmInternalMessageDefaultContextLang { get; set; }
        DbSet<CrmInternalMessageDetails> CrmInternalMessageDetails { get; set; }
        DbSet<CrmInternalMessageGroup> CrmInternalMessageGroup { get; set; }
        DbSet<CrmInternalMessageGroupLang> CrmInternalMessageGroupLang { get; set; }
        DbSet<CrmInternalMessageLang> CrmInternalMessageLang { get; set; }
        DbSet<CrmInternalMessagePriority> CrmInternalMessagePriority { get; set; }
        DbSet<CrmInternalMessagePriorityLang> CrmInternalMessagePriorityLang { get; set; }
        DbSet<CrmInternalMessageSelectReceiver> CrmInternalMessageSelectReceiver { get; set; }
        DbSet<CrmInternalMessageTreeType> CrmInternalMessageTreeType { get; set; }
        DbSet<CrmInternalMessageTreeTypeLang> CrmInternalMessageTreeTypeLang { get; set; }
        DbSet<CrmInternalMessageType> CrmInternalMessageType { get; set; }
        DbSet<CrmInternalMessageTypeLang> CrmInternalMessageTypeLang { get; set; }
        DbSet<CrmKnowledgeTank> CrmKnowledgeTank { get; set; }
        DbSet<CrmKnowledgeTankGroup> CrmKnowledgeTankGroup { get; set; }
        DbSet<CrmKnowledgeTankGroupLang> CrmKnowledgeTankGroupLang { get; set; }
        DbSet<CrmKnowledgeTankGroupPermission> CrmKnowledgeTankGroupPermission { get; set; }
        DbSet<CrmKnowledgeTankLang> CrmKnowledgeTankLang { get; set; }
        DbSet<CrmKnowledgeTankPriority> CrmKnowledgeTankPriority { get; set; }
        DbSet<CrmKnowledgeTankPriorityLang> CrmKnowledgeTankPriorityLang { get; set; }
        DbSet<CrmLeave> CrmLeave { get; set; }
        DbSet<CrmLeaveKinds> CrmLeaveKinds { get; set; }
        DbSet<CrmLeaveStatus> CrmLeaveStatus { get; set; }
        DbSet<CrmLeaveStayType> CrmLeaveStayType { get; set; }
        DbSet<CrmLeaveType> CrmLeaveType { get; set; }
        DbSet<CrmLeaveVehicleType> CrmLeaveVehicleType { get; set; }
        DbSet<CrmLinkAccNoAvSetting> CrmLinkAccNoAvSetting { get; set; }
        DbSet<CrmLinkAccNoAvSettingDetails> CrmLinkAccNoAvSettingDetails { get; set; }
        DbSet<CrmLinkAccNoAvSettingDetailsLang> CrmLinkAccNoAvSettingDetailsLang { get; set; }
        DbSet<CrmLinkAccNoAvSettingLang> CrmLinkAccNoAvSettingLang { get; set; }
        DbSet<CrmLinkAccSetting> CrmLinkAccSetting { get; set; }
        DbSet<CrmLinkAccSettingDetails> CrmLinkAccSettingDetails { get; set; }
        DbSet<CrmLinkAccSettingDetailsLang> CrmLinkAccSettingDetailsLang { get; set; }
        DbSet<CrmLinkAccSettingLang> CrmLinkAccSettingLang { get; set; }
        DbSet<CrmLinkAccSystems> CrmLinkAccSystems { get; set; }
        DbSet<CrmLinkAccTarazSetting> CrmLinkAccTarazSetting { get; set; }
        DbSet<CrmLinkAccTarazSettingDetails> CrmLinkAccTarazSettingDetails { get; set; }
        DbSet<CrmLinkAccTarazSettingDetailsLang> CrmLinkAccTarazSettingDetailsLang { get; set; }
        DbSet<CrmLinkAccTarazSettingLang> CrmLinkAccTarazSettingLang { get; set; }
        DbSet<CrmLinkedCompany> CrmLinkedCompany { get; set; }
        DbSet<CrmLinkedType> CrmLinkedType { get; set; }
        DbSet<CrmLinkedTypeLang> CrmLinkedTypeLang { get; set; }
        DbSet<CrmLinkedUsers> CrmLinkedUsers { get; set; }
        DbSet<CrmOperationsType> CrmOperationsType { get; set; }
        DbSet<CrmOperationsTypeLang> CrmOperationsTypeLang { get; set; }
        DbSet<CrmPersonDepartments> CrmPersonDepartments { get; set; }
        DbSet<CrmPersonDepartmentsLang> CrmPersonDepartmentsLang { get; set; }
        DbSet<CrmPersonGroups> CrmPersonGroups { get; set; }
        DbSet<CrmPersonGroupsLang> CrmPersonGroupsLang { get; set; }
        DbSet<CrmPersonJobs> CrmPersonJobs { get; set; }
        DbSet<CrmPersonJobsLang> CrmPersonJobsLang { get; set; }
        DbSet<CrmPersonPicture> CrmPersonPicture { get; set; }
        DbSet<CrmPersonTitle> CrmPersonTitle { get; set; }
        DbSet<CrmPersonTitleLang> CrmPersonTitleLang { get; set; }
        DbSet<CrmPersonType> CrmPersonType { get; set; }
        DbSet<CrmPersonTypeLang> CrmPersonTypeLang { get; set; }
        DbSet<CrmProjectDefualtValue> CrmProjectDefualtValue { get; set; }
        DbSet<CrmProjectDefualtValueLang> CrmProjectDefualtValueLang { get; set; }
        DbSet<CrmProjectFieldTitle> CrmProjectFieldTitle { get; set; }
        DbSet<CrmProjectFieldTitleLang> CrmProjectFieldTitleLang { get; set; }
        DbSet<CrmProjectFieldValueType> CrmProjectFieldValueType { get; set; }
        DbSet<CrmProjectGrade> CrmProjectGrade { get; set; }
        DbSet<CrmProjectGradeLang> CrmProjectGradeLang { get; set; }
        DbSet<CrmProjectGroups> CrmProjectGroups { get; set; }
        DbSet<CrmProjectGroupsLang> CrmProjectGroupsLang { get; set; }
        DbSet<CrmProjectGroupsMulti> CrmProjectGroupsMulti { get; set; }
        DbSet<CrmProjectGroupsMultiI> CrmProjectGroupsMultiI { get; set; }
        DbSet<CrmProjectGroupsMultiILang> CrmProjectGroupsMultiILang { get; set; }
        DbSet<CrmProjectGroupsMultiLang> CrmProjectGroupsMultiLang { get; set; }
        DbSet<CrmProjectInformations> CrmProjectInformations { get; set; }
        DbSet<CrmProjectInformationsLang> CrmProjectInformationsLang { get; set; }
        DbSet<CrmProjectMultiGroups> CrmProjectMultiGroups { get; set; }
        DbSet<CrmProjectMultiIgroups> CrmProjectMultiIgroups { get; set; }
        DbSet<CrmProjectPriority> CrmProjectPriority { get; set; }
        DbSet<CrmProjectPriorityLang> CrmProjectPriorityLang { get; set; }
        DbSet<CrmProjectTitles> CrmProjectTitles { get; set; }
        DbSet<CrmProjectTitlesLang> CrmProjectTitlesLang { get; set; }
        DbSet<CrmProjects> CrmProjects { get; set; }
        DbSet<CrmProjectsForbiddenForUser> CrmProjectsForbiddenForUser { get; set; }
        DbSet<CrmProjectsForbiddenForUserLang> CrmProjectsForbiddenForUserLang { get; set; }
        DbSet<CrmProjectsLang> CrmProjectsLang { get; set; }
        DbSet<CrmProjectsTmp> CrmProjectsTmp { get; set; }
        DbSet<CrmProjectsTmpLang> CrmProjectsTmpLang { get; set; }
        DbSet<CrmShowTableFieldInFo> CrmShowTableFieldInFo { get; set; }
        DbSet<CrmSystemParts> CrmSystemParts { get; set; }
        DbSet<CrmSystemPartsLang> CrmSystemPartsLang { get; set; }
        DbSet<CrmTelegBotChatMessage> CrmTelegBotChatMessage { get; set; }
        DbSet<CrmTelegBotContacts> CrmTelegBotContacts { get; set; }
        DbSet<CrmTelegBotMessageType> CrmTelegBotMessageType { get; set; }
        DbSet<CrmTelegBotSetting> CrmTelegBotSetting { get; set; }
        DbSet<CrmTelegChatMessage> CrmTelegChatMessage { get; set; }
        DbSet<CrmTelegContacts> CrmTelegContacts { get; set; }
        DbSet<CrmTelegMessageType> CrmTelegMessageType { get; set; }
        DbSet<CrmTelegSetting> CrmTelegSetting { get; set; }
        DbSet<CrmTempEmails> CrmTempEmails { get; set; }
        DbSet<CrmTimeAttendance> CrmTimeAttendance { get; set; }
        DbSet<CrmTimeAttendanceBase> CrmTimeAttendanceBase { get; set; }
        DbSet<CrmTimeAttendanceLog> CrmTimeAttendanceLog { get; set; }
        DbSet<CrmUserNotes> CrmUserNotes { get; set; }
        DbSet<CrmUserTaskGroups> CrmUserTaskGroups { get; set; }
        DbSet<CrmUserTaskGroupsLang> CrmUserTaskGroupsLang { get; set; }
        DbSet<CrmUserTaskPriorities> CrmUserTaskPriorities { get; set; }
        DbSet<CrmUserTaskPrioritiesLang> CrmUserTaskPrioritiesLang { get; set; }
        DbSet<CrmUserTasks> CrmUserTasks { get; set; }
        DbSet<CrmUserTasksLang> CrmUserTasksLang { get; set; }
        DbSet<CrmVersionUpgrade> CrmVersionUpgrade { get; set; }
        DbSet<CrmVersionUpgradeDetails> CrmVersionUpgradeDetails { get; set; }
        DbSet<CrmVersions> CrmVersions { get; set; }
        DbSet<CrmWebSetting> CrmWebSetting { get; set; }
        DbSet<CrmsysCideviceType> CrmsysCideviceType { get; set; }
        DbSet<CrmsysCipopUpSetting> CrmsysCipopUpSetting { get; set; }
        DbSet<CrmsysCisetting> CrmsysCisetting { get; set; }
        DbSet<CrmsysDbobjects> CrmsysDbobjects { get; set; }
        DbSet<CrmsysDbobjectsLang> CrmsysDbobjectsLang { get; set; }
        DbSet<CrmsysDbtempInfo> CrmsysDbtempInfo { get; set; }
        DbSet<CrmsysDbtempInfoType> CrmsysDbtempInfoType { get; set; }
        DbSet<CrmsysFormActions> CrmsysFormActions { get; set; }
        DbSet<CrmsysFormActionsLang> CrmsysFormActionsLang { get; set; }
        DbSet<CrmsysFormObjectProperties> CrmsysFormObjectProperties { get; set; }
        DbSet<CrmsysFormObjectPropertiesLang> CrmsysFormObjectPropertiesLang { get; set; }
        DbSet<CrmsysForms> CrmsysForms { get; set; }
        DbSet<CrmsysFormsLang> CrmsysFormsLang { get; set; }
        DbSet<CrmsysManageAlarmChanges> CrmsysManageAlarmChanges { get; set; }
        DbSet<CrmsysManageInternalMessageChanges> CrmsysManageInternalMessageChanges { get; set; }
        DbSet<CrmsysRollPermission> CrmsysRollPermission { get; set; }
        DbSet<CrmsysRolls> CrmsysRolls { get; set; }
        DbSet<CrmsysRollsLang> CrmsysRollsLang { get; set; }
        DbSet<CrmsysSetting> CrmsysSetting { get; set; }
        DbSet<CrmsysSettingLang> CrmsysSettingLang { get; set; }
        DbSet<CrmtmpManageTellNumber> CrmtmpManageTellNumber { get; set; }
        DbSet<Education> Education { get; set; }
        DbSet<EducationLang> EducationLang { get; set; }
        DbSet<EmailDefaultBodyText> EmailDefaultBodyText { get; set; }
        DbSet<EmailDefaultBodyTextLang> EmailDefaultBodyTextLang { get; set; }
        DbSet<EmailReceive> EmailReceive { get; set; }
        DbSet<EmailReceiveAttachments> EmailReceiveAttachments { get; set; }
        DbSet<EmailReceiveFolders> EmailReceiveFolders { get; set; }
        DbSet<EmailSendAttachment> EmailSendAttachment { get; set; }
        DbSet<EmailSendDetail> EmailSendDetail { get; set; }
        DbSet<EmailSendHeader> EmailSendHeader { get; set; }
        DbSet<EmailSetting> EmailSetting { get; set; }
        DbSet<EmailUserDefaultSetting> EmailUserDefaultSetting { get; set; }
        DbSet<EmailUserTempTank> EmailUserTempTank { get; set; }
        DbSet<EmailUsersInfo> EmailUsersInfo { get; set; }
        DbSet<Languages> Languages { get; set; }
        DbSet<MobApiAndTableDetail> MobApiAndTableDetail { get; set; }
        DbSet<MobCompanyAppInfo> MobCompanyAppInfo { get; set; }
        DbSet<MobErrorLogs> MobErrorLogs { get; set; }
        DbSet<MyWebsites> MyWebsites { get; set; }
        DbSet<PayRollItemTypes> PayRollItemTypes { get; set; }
        DbSet<PayRollItemTypesLang> PayRollItemTypesLang { get; set; }
        DbSet<PayRollItems> PayRollItems { get; set; }
        DbSet<PayRollItemsLang> PayRollItemsLang { get; set; }
        DbSet<PayRollUserCycle> PayRollUserCycle { get; set; }
        DbSet<PayRollUserCycleItemValues> PayRollUserCycleItemValues { get; set; }
        DbSet<PayRollUserCycleLang> PayRollUserCycleLang { get; set; }
        DbSet<PayRollUserDefaultItems> PayRollUserDefaultItems { get; set; }
        DbSet<PayRollUserPaymentTypes> PayRollUserPaymentTypes { get; set; }
        DbSet<PayRollUserPaymentTypesLang> PayRollUserPaymentTypesLang { get; set; }
        DbSet<PayRollUserPayments> PayRollUserPayments { get; set; }
        DbSet<PayRollUserPaymentsLang> PayRollUserPaymentsLang { get; set; }
        DbSet<PrintFormat> PrintFormat { get; set; }
        DbSet<PrintFormatLang> PrintFormatLang { get; set; }
        DbSet<PrintFormatType> PrintFormatType { get; set; }
        DbSet<PrintFormatTypeLang> PrintFormatTypeLang { get; set; }
        DbSet<Projects> Projects { get; set; }
        DbSet<ProjectsLang> ProjectsLang { get; set; }
        DbSet<Province> Province { get; set; }
        DbSet<ProvinceLang> ProvinceLang { get; set; }
        DbSet<SecLetterDefaultSettings> SecLetterDefaultSettings { get; set; }
        DbSet<SecLetterDefaultSettingsLang> SecLetterDefaultSettingsLang { get; set; }
        DbSet<SecLetterType> SecLetterType { get; set; }
        DbSet<SecLetterTypeLang> SecLetterTypeLang { get; set; }
        DbSet<SecLetters> SecLetters { get; set; }
        DbSet<SecLettersLang> SecLettersLang { get; set; }
        DbSet<Sex> Sex { get; set; }
        DbSet<SexLang> SexLang { get; set; }
        DbSet<SmsDefaultBodyText> SmsDefaultBodyText { get; set; }
        DbSet<SmsDefaultBodyTextGroups> SmsDefaultBodyTextGroups { get; set; }
        DbSet<SmsDefaultBodyTextGroupsLang> SmsDefaultBodyTextGroupsLang { get; set; }
        DbSet<SmsDefaultBodyTextLang> SmsDefaultBodyTextLang { get; set; }
        DbSet<SmsDeliveryStatus> SmsDeliveryStatus { get; set; }
        DbSet<SmsDeliveryStatusLang> SmsDeliveryStatusLang { get; set; }
        DbSet<SmsGsmmodemDelivery> SmsGsmmodemDelivery { get; set; }
        DbSet<SmsGsmmodemSetting> SmsGsmmodemSetting { get; set; }
        DbSet<SmsGsmreceives> SmsGsmreceives { get; set; }
        DbSet<SmsGsmsendingTank> SmsGsmsendingTank { get; set; }
        DbSet<SmsProviders> SmsProviders { get; set; }
        DbSet<SmsReceive> SmsReceive { get; set; }
        DbSet<SmsReceiveFromWsdl> SmsReceiveFromWsdl { get; set; }
        DbSet<SmsSendDetail> SmsSendDetail { get; set; }
        DbSet<SmsSendHeader> SmsSendHeader { get; set; }
        DbSet<SmsSendType> SmsSendType { get; set; }
        DbSet<SmsSendTypeLang> SmsSendTypeLang { get; set; }
        DbSet<SmsSetting> SmsSetting { get; set; }
        DbSet<SmsTempMobileNumbers> SmsTempMobileNumbers { get; set; }
        DbSet<SmsUserSendCredit> SmsUserSendCredit { get; set; }
        DbSet<SmsUserSendCreditLang> SmsUserSendCreditLang { get; set; }
        DbSet<UserDepartmentTicketReferUsers> UserDepartmentTicketReferUsers { get; set; }
        DbSet<UserDepartments> UserDepartments { get; set; }
        DbSet<UserDepartmentsLang> UserDepartmentsLang { get; set; }
        DbSet<UserLanguages> UserLanguages { get; set; }
        DbSet<UserLoginAllowedTimes> UserLoginAllowedTimes { get; set; }
        DbSet<UserSignature> UserSignature { get; set; }
        DbSet<Users> Users { get; set; }
        DbSet<UsersLang> UsersLang { get; set; }
        DbSet<UsersPermission> UsersPermission { get; set; }
        DbSet<UsersPermissionLang> UsersPermissionLang { get; set; }
        DbSet<WsWareHouse> WsWareHouse { get; set; }
        DbSet<WsWareHouseLang> WsWareHouseLang { get; set; }
        DbSet<WsbuyOrder> WsbuyOrder { get; set; }
        DbSet<WsbuyOrderItemSerials> WsbuyOrderItemSerials { get; set; }
        DbSet<WsbuyOrderItemSerialsLang> WsbuyOrderItemSerialsLang { get; set; }
        DbSet<WsbuyOrderItems> WsbuyOrderItems { get; set; }
        DbSet<WsbuyOrderItemsLang> WsbuyOrderItemsLang { get; set; }
        DbSet<WsbuyOrderLang> WsbuyOrderLang { get; set; }
        DbSet<WsbuyOrderOpr> WsbuyOrderOpr { get; set; }
        DbSet<WsbuyOrderOprLang> WsbuyOrderOprLang { get; set; }
        DbSet<WsbuyOrderPaymentTypes> WsbuyOrderPaymentTypes { get; set; }
        DbSet<WsbuyOrderPaymentTypesLang> WsbuyOrderPaymentTypesLang { get; set; }
        DbSet<WsbuyOrderPayments> WsbuyOrderPayments { get; set; }
        DbSet<WsbuyOrderPaymentsLang> WsbuyOrderPaymentsLang { get; set; }
        DbSet<WsbuyOrderStatus> WsbuyOrderStatus { get; set; }
        DbSet<WsbuyOrderStatusLang> WsbuyOrderStatusLang { get; set; }
        DbSet<WscreditDuration> WscreditDuration { get; set; }
        DbSet<WscreditDurationLang> WscreditDurationLang { get; set; }
        DbSet<WscurrencyUnits> WscurrencyUnits { get; set; }
        DbSet<WscurrencyUnitsLang> WscurrencyUnitsLang { get; set; }
        DbSet<WsdeliveryTime> WsdeliveryTime { get; set; }
        DbSet<WsdeliveryTimeLang> WsdeliveryTimeLang { get; set; }
        DbSet<Wsdoc> Wsdoc { get; set; }
        DbSet<WsdocItemSerials> WsdocItemSerials { get; set; }
        DbSet<WsdocItemSerialsLang> WsdocItemSerialsLang { get; set; }
        DbSet<WsdocItems> WsdocItems { get; set; }
        DbSet<WsdocItemsLang> WsdocItemsLang { get; set; }
        DbSet<WsdocLang> WsdocLang { get; set; }
        DbSet<WsdocOpr> WsdocOpr { get; set; }
        DbSet<WsdocOprLang> WsdocOprLang { get; set; }
        DbSet<WsfinancialPeriod> WsfinancialPeriod { get; set; }
        DbSet<Wsguaranty> Wsguaranty { get; set; }
        DbSet<WsguarantyLang> WsguarantyLang { get; set; }
        DbSet<WslinkedProducts> WslinkedProducts { get; set; }
        DbSet<Wslogo> Wslogo { get; set; }
        DbSet<WslogoLang> WslogoLang { get; set; }
        DbSet<Wsorder> Wsorder { get; set; }
        DbSet<WsorderCommissionPayTypes> WsorderCommissionPayTypes { get; set; }
        DbSet<WsorderCommissionPayTypesLang> WsorderCommissionPayTypesLang { get; set; }
        DbSet<WsorderCommissions> WsorderCommissions { get; set; }
        DbSet<WsorderCommissionsLang> WsorderCommissionsLang { get; set; }
        DbSet<WsorderDefaultSetting> WsorderDefaultSetting { get; set; }
        DbSet<WsorderDefaultSettingLang> WsorderDefaultSettingLang { get; set; }
        DbSet<WsorderItemSerials> WsorderItemSerials { get; set; }
        DbSet<WsorderItemSerialsLang> WsorderItemSerialsLang { get; set; }
        DbSet<WsorderItems> WsorderItems { get; set; }
        DbSet<WsorderItemsLang> WsorderItemsLang { get; set; }
        DbSet<WsorderLang> WsorderLang { get; set; }
        DbSet<WsorderOpr> WsorderOpr { get; set; }
        DbSet<WsorderOprLang> WsorderOprLang { get; set; }
        DbSet<WsorderPaymentTypes> WsorderPaymentTypes { get; set; }
        DbSet<WsorderPaymentTypesLang> WsorderPaymentTypesLang { get; set; }
        DbSet<WsorderPayments> WsorderPayments { get; set; }
        DbSet<WsorderPaymentsLang> WsorderPaymentsLang { get; set; }
        DbSet<WsorderStatus> WsorderStatus { get; set; }
        DbSet<WsorderStatusLang> WsorderStatusLang { get; set; }
        DbSet<WspayCondition> WspayCondition { get; set; }
        DbSet<WspayConditionLang> WspayConditionLang { get; set; }
        DbSet<WspreOrder> WspreOrder { get; set; }
        DbSet<WspreOrderDefaultSetting> WspreOrderDefaultSetting { get; set; }
        DbSet<WspreOrderDefaultSettingLang> WspreOrderDefaultSettingLang { get; set; }
        DbSet<WspreOrderItemSpecification> WspreOrderItemSpecification { get; set; }
        DbSet<WspreOrderItemSpecificationLang> WspreOrderItemSpecificationLang { get; set; }
        DbSet<WspreOrderItems> WspreOrderItems { get; set; }
        DbSet<WspreOrderItemsLang> WspreOrderItemsLang { get; set; }
        DbSet<WspreOrderLang> WspreOrderLang { get; set; }
        DbSet<WspreOrderOpr> WspreOrderOpr { get; set; }
        DbSet<WspreOrderOprLang> WspreOrderOprLang { get; set; }
        DbSet<WspreOrderPayments> WspreOrderPayments { get; set; }
        DbSet<WspreOrderPaymentsLang> WspreOrderPaymentsLang { get; set; }
        DbSet<WspreOrderPrdGroupMustExistReasonGroups> WspreOrderPrdGroupMustExistReasonGroups { get; set; }
        DbSet<WspreOrderPrdGroupMustExistReasonGroupsLang> WspreOrderPrdGroupMustExistReasonGroupsLang { get; set; }
        DbSet<WspreOrderPrdGroupMustExistReasons> WspreOrderPrdGroupMustExistReasons { get; set; }
        DbSet<WspreOrderPrdGroupMustExistReasonsLang> WspreOrderPrdGroupMustExistReasonsLang { get; set; }
        DbSet<WspreOrderStatus> WspreOrderStatus { get; set; }
        DbSet<WspreOrderStatusLang> WspreOrderStatusLang { get; set; }
        DbSet<WsproductColor> WsproductColor { get; set; }
        DbSet<WsproductColorLang> WsproductColorLang { get; set; }
        DbSet<WsproductCost> WsproductCost { get; set; }
        DbSet<WsproductCostGroup> WsproductCostGroup { get; set; }
        DbSet<WsproductCostGroupLang> WsproductCostGroupLang { get; set; }
        DbSet<WsproductCostLang> WsproductCostLang { get; set; }
        DbSet<WsproductFirstGroup> WsproductFirstGroup { get; set; }
        DbSet<WsproductFirstGroupLang> WsproductFirstGroupLang { get; set; }
        DbSet<WsproductGallery> WsproductGallery { get; set; }
        DbSet<WsproductImportFromExcel> WsproductImportFromExcel { get; set; }
        DbSet<WsproductImportFromExcelFields> WsproductImportFromExcelFields { get; set; }
        DbSet<WsproductImportFromExcelFieldsLang> WsproductImportFromExcelFieldsLang { get; set; }
        DbSet<WsproductPicture> WsproductPicture { get; set; }
        DbSet<WsproductPictureLang> WsproductPictureLang { get; set; }
        DbSet<WsproductPrice> WsproductPrice { get; set; }
        DbSet<WsproductPriceGroup> WsproductPriceGroup { get; set; }
        DbSet<WsproductPriceGroupLang> WsproductPriceGroupLang { get; set; }
        DbSet<WsproductPriceLang> WsproductPriceLang { get; set; }
        DbSet<WsproductSecondGroup> WsproductSecondGroup { get; set; }
        DbSet<WsproductSecondGroupLang> WsproductSecondGroupLang { get; set; }
        DbSet<WsproductShpStockManageTypes> WsproductShpStockManageTypes { get; set; }
        DbSet<WsproductShpStockManageTypesLang> WsproductShpStockManageTypesLang { get; set; }
        DbSet<WsproductSpecification> WsproductSpecification { get; set; }
        DbSet<WsproductSpecificationLang> WsproductSpecificationLang { get; set; }
        DbSet<WsproductUnits> WsproductUnits { get; set; }
        DbSet<WsproductUnitsLang> WsproductUnitsLang { get; set; }
        DbSet<Wsproducts> Wsproducts { get; set; }
        DbSet<WsproductsLang> WsproductsLang { get; set; }
        DbSet<WsproductsRate> WsproductsRate { get; set; }
        DbSet<WsproductsUserDiscount> WsproductsUserDiscount { get; set; }
        DbSet<WsproductsUserDiscountLang> WsproductsUserDiscountLang { get; set; }
        DbSet<WsregisterBarCode> WsregisterBarCode { get; set; }
        DbSet<WssettlementType> WssettlementType { get; set; }
        DbSet<WssettlementTypeLang> WssettlementTypeLang { get; set; }
        DbSet<Wssignature> Wssignature { get; set; }
        DbSet<WstmpEnterBarcodeOperation> WstmpEnterBarcodeOperation { get; set; }
        DbSet<WstmpEnterDocPrdWithBarcode> WstmpEnterDocPrdWithBarcode { get; set; }
        DbSet<WstmpUserItemCopy> WstmpUserItemCopy { get; set; }
        DbSet<WsuserFavproductItems> WsuserFavproductItems { get; set; }
        DbSet<WsuserFavproductItemsLang> WsuserFavproductItemsLang { get; set; }
        DbSet<WsuserFavproducts> WsuserFavproducts { get; set; }
        DbSet<WsuserFavproductsLang> WsuserFavproductsLang { get; set; }
        DbSet<WsverificationRequestDetails> WsverificationRequestDetails { get; set; }
        DbSet<WsverificationRequestDetailsLang> WsverificationRequestDetailsLang { get; set; }
        DbSet<WsverificationRequests> WsverificationRequests { get; set; }
        DbSet<WsverificationRequestsLang> WsverificationRequestsLang { get; set; }
        DbSet<WsverificationWorkFlowSteps> WsverificationWorkFlowSteps { get; set; }
        DbSet<WsverificationWorkFlowStepsLang> WsverificationWorkFlowStepsLang { get; set; }
        DbSet<WsverificationWorkFlows> WsverificationWorkFlows { get; set; }
        DbSet<WsverificationWorkFlowsLang> WsverificationWorkFlowsLang { get; set; }




        int SaveChanges(bool acceptAllChangesSuccess);
        int SaveChanges();
        Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = new CancellationToken());
        Task<int> SaveChangesAsync(CancellationToken cancellationToken = new CancellationToken());

    }
}
