// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Contexts;

namespace Persistence.Migrations.IdentityDatabase
{
    [DbContext(typeof(IdentityDatabaseContext))]
    partial class IdentityDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Users.Claims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsHead")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimName = "داشبورد",
                            ClaimType = "Home",
                            ClaimValue = "Home",
                            IsHead = true
                        },
                        new
                        {
                            Id = 2,
                            ClaimName = "مدیریت دسته بندی مجله",
                            ClaimType = "BlogCategories",
                            ClaimValue = "BlogCategories",
                            IsHead = true
                        },
                        new
                        {
                            Id = 3,
                            ClaimName = "مشاهده دسته بندی مجله ها",
                            ClaimType = "BlogCategoriesIndex",
                            ClaimValue = "BlogCategoriesIndex",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 4,
                            ClaimName = "ساخت دسته بندی مجله",
                            ClaimType = "BlogCategoriesCreate",
                            ClaimValue = "BlogCategoriesCreate",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 5,
                            ClaimName = "ویرایش دسته بندی مجله",
                            ClaimType = "BlogCategoriesEdit",
                            ClaimValue = "BlogCategoriesEdit",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 6,
                            ClaimName = "حذف دسته بندی مجله",
                            ClaimType = "BlogCategoriesDelete",
                            ClaimValue = "BlogCategoriesDelete",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 7,
                            ClaimName = "مدیریت مجله",
                            ClaimType = "Blogs",
                            ClaimValue = "Blogs",
                            IsHead = true
                        },
                        new
                        {
                            Id = 8,
                            ClaimName = "مشاهده مجله ها",
                            ClaimType = "BlogsIndex",
                            ClaimValue = "BlogsIndex",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 9,
                            ClaimName = "ساخت مجله",
                            ClaimType = "BlogsCreate",
                            ClaimValue = "BlogsCreate",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 10,
                            ClaimName = "ویرایش مجله",
                            ClaimType = "BlogsEdit",
                            ClaimValue = "BlogsEdit",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 11,
                            ClaimName = "حذف مجله",
                            ClaimType = "BlogsDelete",
                            ClaimValue = "BlogsDelete",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 12,
                            ClaimName = "غیرفعال کردن مجله",
                            ClaimType = "BlogsActive",
                            ClaimValue = "BlogsActive",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 13,
                            ClaimName = "مدیریت شرکت ها",
                            ClaimType = "Company",
                            ClaimValue = "Company",
                            IsHead = true
                        },
                        new
                        {
                            Id = 14,
                            ClaimName = "مدیریت منوها",
                            ClaimType = "Menus",
                            ClaimValue = "Menus",
                            IsHead = true
                        },
                        new
                        {
                            Id = 15,
                            ClaimName = "مدیریت محصولات",
                            ClaimType = "Products",
                            ClaimValue = "Products",
                            IsHead = true
                        },
                        new
                        {
                            Id = 16,
                            ClaimName = "نمایش محصولات",
                            ClaimType = "ProductsIndex",
                            ClaimValue = "ProductsIndex",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 17,
                            ClaimName = "ساخت محصول",
                            ClaimType = "ProductsCreate",
                            ClaimValue = "ProductsCreate",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 18,
                            ClaimName = "ویرایش محصول",
                            ClaimType = "ProductsEdit",
                            ClaimValue = "ProductsEdit",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 19,
                            ClaimName = "حذف محصول",
                            ClaimType = "ProductsDelete",
                            ClaimValue = "ProductsDelete",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 20,
                            ClaimName = "غیر فعال کردن محصول",
                            ClaimType = "ProductsActive",
                            ClaimValue = "ProductsActive",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 21,
                            ClaimName = "مدیریت اسلایدرها",
                            ClaimType = "Sliders",
                            ClaimValue = "Sliders",
                            IsHead = true
                        },
                        new
                        {
                            Id = 22,
                            ClaimName = "مدیریت یوزر ها",
                            ClaimType = "Users",
                            ClaimValue = "Users",
                            IsHead = true
                        },
                        new
                        {
                            Id = 23,
                            ClaimName = "نمایش همه یوزر ها",
                            ClaimType = "UsersIndex",
                            ClaimValue = "UsersIndex",
                            ParentId = 22
                        },
                        new
                        {
                            Id = 24,
                            ClaimName = "ویرایش یوزر",
                            ClaimType = "UsersEdit",
                            ClaimValue = "UsersEdit",
                            ParentId = 22
                        },
                        new
                        {
                            Id = 25,
                            ClaimName = "فایل منیجر",
                            ClaimType = "FileManagers",
                            ClaimValue = "FileManagers",
                            IsHead = true
                        },
                        new
                        {
                            Id = 26,
                            ClaimName = "ویرایش فوتر",
                            ClaimType = "Footers",
                            ClaimValue = "Footers",
                            IsHead = true
                        },
                        new
                        {
                            Id = 27,
                            ClaimName = "ویرایش درباره ما",
                            ClaimType = "AboutUs",
                            ClaimValue = "AboutUs",
                            IsHead = true
                        },
                        new
                        {
                            Id = 28,
                            ClaimName = "ویرایش ارتباط با ما",
                            ClaimType = "ContactUs",
                            ClaimValue = "ContactUs",
                            IsHead = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role", "dbo");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole<string>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "Home",
                            ClaimValue = "Home",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "BlogCategories",
                            ClaimValue = "BlogCategories",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "BlogCategoriesIndex",
                            ClaimValue = "BlogCategoriesIndex",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "BlogCategoriesCreate",
                            ClaimValue = "BlogCategoriesCreate",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "BlogCategoriesEdit",
                            ClaimValue = "BlogCategoriesEdit",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "BlogCategoriesDelete",
                            ClaimValue = "BlogCategoriesDelete",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "Blogs",
                            ClaimValue = "Blogs",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "BlogsIndex",
                            ClaimValue = "BlogsIndex",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "BlogsCreate",
                            ClaimValue = "BlogsCreate",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "BlogsEdit",
                            ClaimValue = "BlogsEdit",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "BlogsDelete",
                            ClaimValue = "BlogsDelete",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "BlogsActive",
                            ClaimValue = "BlogsActive",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "Company",
                            ClaimValue = "Company",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "Menus",
                            ClaimValue = "Menus",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "Products",
                            ClaimValue = "Products",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "ProductsIndex",
                            ClaimValue = "ProductsIndex",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "ProductsCreate",
                            ClaimValue = "ProductsCreate",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "ProductsEdit",
                            ClaimValue = "ProductsEdit",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "ProductsDelete",
                            ClaimValue = "ProductsDelete",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "ProductsActive",
                            ClaimValue = "ProductsActive",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "Sliders",
                            ClaimValue = "Sliders",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "Users",
                            ClaimValue = "Users",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "UsersIndex",
                            ClaimValue = "UsersIndex",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "UsersEdit",
                            ClaimValue = "UsersEdit",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "Factory",
                            ClaimValue = "Factory",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 26,
                            ClaimType = "FileManagers",
                            ClaimValue = "FileManagers",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 27,
                            ClaimType = "Footers",
                            ClaimValue = "Footers",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 28,
                            ClaimType = "AboutUs",
                            ClaimValue = "AboutUs",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            Id = 29,
                            ClaimType = "ContactUs",
                            ClaimValue = "ContactUs",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", "dbo");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser<string>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProviderKey", "LoginProvider");

                    b.ToTable("UserLogins", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles", "dbo");

                    b.HasData(
                        new
                        {
                            UserId = "6a64e206-d6c0-4386-923f-5104f173e01c",
                            RoleId = "8ce221cd-1b57-4e0b-8781-79524b05fcc5"
                        },
                        new
                        {
                            UserId = "5a64e206-d6c0-4386-923f-5104f173e01c",
                            RoleId = "2bb43ab4-61c4-4435-aa3e-c6ab7b2858d1"
                        },
                        new
                        {
                            UserId = "4a64e206-d6c0-4386-923f-5104f173e01c",
                            RoleId = "7990ad8a-92a8-4cda-918c-b71887047e9e"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider");

                    b.ToTable("UserTokens", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.Users.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole<string>");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Role");

                    b.HasData(
                        new
                        {
                            Id = "8ce221cd-1b57-4e0b-8781-79524b05fcc5",
                            ConcurrencyStamp = "e27bb24c-7f4a-45f7-b35b-bdf0068d9ff4",
                            Name = "SeniorProgrammer",
                            NormalizedName = "SENIORPROGRAMMER",
                            Description = "برنامه نویس"
                        },
                        new
                        {
                            Id = "2bb43ab4-61c4-4435-aa3e-c6ab7b2858d1",
                            ConcurrencyStamp = "7990ad8a-92a8-4cda-918c-b71887047e9e",
                            Name = "User",
                            NormalizedName = "USER",
                            Description = "خریدار"
                        },
                        new
                        {
                            Id = "7990ad8a-92a8-4cda-918c-b71887047e9e",
                            ConcurrencyStamp = "2bb43ab4-61c4-4435-aa3e-c6ab7b2858de",
                            Name = "Owner",
                            NormalizedName = "OWNER",
                            Description = "فروشنده"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser<string>");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<int>("CrmUsersId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequestToBeOwner")
                        .HasColumnType("bit");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "6a64e206-d6c0-4386-923f-5104f173e01c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5927a97d-ea14-4449-9efa-7d5ab4b957e5",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedUserName = "09129283406",
                            PasswordHash = "AQAAAAEAACcQAAAAEPbSX2kOSigd6t402PCkp70rA2gX/1xlFFBZJ8pgJxtwKbY2eZ5Tp2qHOrecBHXCQw==",
                            PhoneNumber = "09129283406",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "IXN7VEICHYB72KXHBCULEPXFHNZ5U6FS",
                            TwoFactorEnabled = false,
                            UserName = "09129283406",
                            Address = "تهران",
                            Credit = 0,
                            CrmUsersId = 1082,
                            DataCreated = new DateTime(2021, 7, 28, 14, 18, 20, 257, DateTimeKind.Local).AddTicks(4794),
                            FirstName = "حسین",
                            IsActive = true,
                            LastName = "کرجی",
                            RequestToBeOwner = false
                        },
                        new
                        {
                            Id = "5a64e206-d6c0-4386-923f-5104f173e01c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5927a97d-ea14-4449-9efa-7d5ab4b957e5",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedUserName = "09129283405",
                            PasswordHash = "AQAAAAEAACcQAAAAEPbSX2kOSigd6t402PCkp70rA2gX/1xlFFBZJ8pgJxtwKbY2eZ5Tp2qHOrecBHXCQw==",
                            PhoneNumber = "09129283405",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "IXN7VEICHYB72KXHBCULEPXFHNZ5U6FS",
                            TwoFactorEnabled = false,
                            UserName = "09129283405",
                            Address = "تهران",
                            Credit = 0,
                            CrmUsersId = 1083,
                            DataCreated = new DateTime(2021, 7, 28, 14, 18, 20, 260, DateTimeKind.Local).AddTicks(817),
                            FirstName = "پنل",
                            IsActive = true,
                            LastName = "خریدار",
                            RequestToBeOwner = false
                        },
                        new
                        {
                            Id = "4a64e206-d6c0-4386-923f-5104f173e01c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5927a97d-ea14-4449-9efa-7d5ab4b957e5",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedUserName = "09129283404",
                            PasswordHash = "AQAAAAEAACcQAAAAEPbSX2kOSigd6t402PCkp70rA2gX/1xlFFBZJ8pgJxtwKbY2eZ5Tp2qHOrecBHXCQw==",
                            PhoneNumber = "09129283404",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "IXN7VEICHYB72KXHBCULEPXFHNZ5U6FS",
                            TwoFactorEnabled = false,
                            UserName = "09129283404",
                            Address = "تهران",
                            Credit = 0,
                            CrmUsersId = 1084,
                            DataCreated = new DateTime(2021, 7, 28, 14, 18, 20, 260, DateTimeKind.Local).AddTicks(871),
                            FirstName = "پنل",
                            IsActive = true,
                            LastName = "فروشنده",
                            RequestToBeOwner = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
