// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Contexts;

namespace Persistence.Migrations.CustomDb
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20210529081326_CreateSlidersClaimsTables")]
    partial class CreateSlidersClaimsTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Sliders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("Domain.Entities.Users.Claims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsHead")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimName = "داشبورد",
                            ClaimType = "Home",
                            ClaimValue = "Home",
                            IsHead = true
                        },
                        new
                        {
                            Id = 2,
                            ClaimName = "مدیریت دسته بندی بلاگ",
                            ClaimType = "BlogCategories",
                            ClaimValue = "BlogCategories",
                            IsHead = true
                        },
                        new
                        {
                            Id = 3,
                            ClaimName = "مشاهده دسته بندی بلاگ ها",
                            ClaimType = "BlogCategoriesIndex",
                            ClaimValue = "BlogCategoriesIndex",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 4,
                            ClaimName = "ساخت دسته بندی بلاگ",
                            ClaimType = "BlogCategoriesCreate",
                            ClaimValue = "BlogCategoriesCreate",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 5,
                            ClaimName = "ویرایش دسته بندی بلاگ",
                            ClaimType = "BlogCategoriesEdit",
                            ClaimValue = "BlogCategoriesEdit",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 6,
                            ClaimName = "حذف دسته بندی بلاگ",
                            ClaimType = "BlogCategoriesDelete",
                            ClaimValue = "BlogCategoriesDelete",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 7,
                            ClaimName = "مدیریت بلاگ",
                            ClaimType = "Blogs",
                            ClaimValue = "Blogs",
                            IsHead = true
                        },
                        new
                        {
                            Id = 8,
                            ClaimName = "BlogsIndex",
                            ClaimType = "BlogsIndex",
                            ClaimValue = "BlogsIndex",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 9,
                            ClaimName = "ساخت بلاگ",
                            ClaimType = "BlogsCreate",
                            ClaimValue = "BlogsCreate",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 10,
                            ClaimName = "ویرایش بلاگ",
                            ClaimType = "BlogsEdit",
                            ClaimValue = "BlogsEdit",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 11,
                            ClaimName = "حذف بلاگ",
                            ClaimType = "BlogsDelete",
                            ClaimValue = "BlogsDelete",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 12,
                            ClaimName = "غیرفعال کردن بلاگ",
                            ClaimType = "BlogsActive",
                            ClaimValue = "BlogsActive",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 13,
                            ClaimName = "مدیریت شرکت ها",
                            ClaimType = "Company",
                            ClaimValue = "Company",
                            IsHead = true
                        },
                        new
                        {
                            Id = 14,
                            ClaimName = "مدیریت منوها",
                            ClaimType = "Menus",
                            ClaimValue = "Menus",
                            IsHead = true
                        },
                        new
                        {
                            Id = 15,
                            ClaimName = "مدیریت محصولات",
                            ClaimType = "Products",
                            ClaimValue = "Products",
                            IsHead = true
                        },
                        new
                        {
                            Id = 16,
                            ClaimName = "نمایش محصولات",
                            ClaimType = "ProductsIndex",
                            ClaimValue = "ProductsIndex",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 17,
                            ClaimName = "ساخت محصول",
                            ClaimType = "ProductsCreate",
                            ClaimValue = "ProductsCreate",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 18,
                            ClaimName = "ویرایش محصول",
                            ClaimType = "ProductsEdit",
                            ClaimValue = "ProductsEdit",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 19,
                            ClaimName = "حذف محصول",
                            ClaimType = "ProductsDelete",
                            ClaimValue = "ProductsDelete",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 20,
                            ClaimName = "غیر فعال کردن محصول",
                            ClaimType = "ProductsActive",
                            ClaimValue = "ProductsActive",
                            ParentId = 15
                        },
                        new
                        {
                            Id = 21,
                            ClaimName = "مدیریت اسلایدرها",
                            ClaimType = "Sliders",
                            ClaimValue = "Sliders",
                            IsHead = true
                        },
                        new
                        {
                            Id = 22,
                            ClaimName = "مدیریت یوزر ها",
                            ClaimType = "Users",
                            ClaimValue = "Users",
                            IsHead = true
                        },
                        new
                        {
                            Id = 23,
                            ClaimName = "نمایش همه یوزر ها",
                            ClaimType = "UsersIndex",
                            ClaimValue = "UsersIndex",
                            ParentId = 22
                        },
                        new
                        {
                            Id = 24,
                            ClaimName = "ویرایش یوزر",
                            ClaimType = "UsersEdit",
                            ClaimValue = "UsersEdit",
                            ParentId = 22
                        });
                });

            modelBuilder.Entity("Domain.Entities.Users.Claims", b =>
                {
                    b.HasOne("Domain.Entities.Users.Claims", "Parent")
                        .WithMany("SubClaims")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Entities.Users.Claims", b =>
                {
                    b.Navigation("SubClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
